version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY} 