providers = ["node"]

[variables]
PORT = "3000"

[phases.install]
cmds = ["cd frontend && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[phases.setup]
cmds = ["npm install -g serve"]

# We only need the static build directory at runtime
[start]
cmd = "npx serve -s frontend/dist -l $PORT" 